### ISSUE TITLE
1.1.2 Todo

### ISSUE THREAD

**Issue by Treetrain1** [FrozenBlock/WilderWild#172]
May be an incomplete list. Add here if needed.

- [x] Add `wilderWild$` prefix to mixins to match new conventions found in `CONTRIBUTING.md`
- [x] Add new config options, (for stone chest, jellyfish, firefly)

**Comment by AViewFromTheTop** [comment]
what do jellyfish need a config for

**Comment by AViewFromTheTop** [comment]
and fireflies
you mean for spawning?

**Comment by Treetrain1** [comment]
Yeah
For stone chests, I’m thinking having a slider for the time before it closes.
For fireflies, a list to add biomes they spawn in
For jellyfish, a list of biomes for non pearlescent ones to spawn in

**Comment by AViewFromTheTop** [comment]
those last two are controlled via datapacks

**Comment by AViewFromTheTop** [comment]
and i have literally no idea how to do HUD/UI stuff, so i can't help much with stone chest sliders

**Comment by Treetrain1** [comment]
> those last two are controlled via datapacks

Oh true

**Comment by Treetrain1** [comment]
> and i have literally no idea how to do HUD/UI stuff, so i can't help much with stone chest sliders

Cloth Config has a thing for it

**Comment by AViewFromTheTop** [comment]
OH YOU MEAN
ok im an idiot i thought you meant for whether or not it'd display a timer for how long it has until closing

**Comment by AViewFromTheTop** [comment]
like a timer at the bottom of the screen while you're in the inventory

**Comment by Treetrain1** [comment]
> like a timer at the bottom of the screen while you're in the inventory

Actually that could be good if done right

**Comment by MerpisMe** [comment]
we could also make it so that the chest slowly closes instead of just suddenly closing

**Comment by MerpisMe** [comment]
so like as soon as it's fully opened it starts slowly closing
also, maybe shift clicking while it's opened will force it to close
i dont really see the idea of shift clicking to open it further tbh, it should just open that much to begin with

**Comment by MerpisMe** [comment]
and if we follow through on the idea of it slowly closing, shift clicking to force close it will make it use the current close sounds. i'm thinking it sliding closed slowly will just use the lift sounds but slowed down

**Comment by AViewFromTheTop** [comment]
> what are your thoughts on this idea? @AViewFromTheTop

I’m so sorry for not replying, I wasn’t checking this repo
Either way that’s actually how I wanted them to work at some point (minus shift-clicking to close,) and it didn’t feel right. Steve and Alex are very cautious people, they’re going to pull their hands back when the lid is slamming. Or, well… You get my point. Or, well, you can’t really search through something like that when the lid’s past a certain point. A heavy lid like that isnt just going to *slowly* tilt back perfectly into place like that, it’s going to *SLAM* down.
Having it slowly close would just make them very wonky, just trust me when I say I think the current iteration is better.
As for the shift-clicking thing, meh. People are going to bitch that they can’t open the chests fast enough. The only reason it only gets to a certain point and opens is because the lid’s high enough to safely search through for a bit without getting your hands sliced off immediately. If the player’s patient enough and messes around enough, they’ll find out about sneaking.

**Comment by AViewFromTheTop** [comment]
It’s one of those small details you’ll slowly learn about in almost every game you play. A little detail that you’ll REALLY appreciate and maybe even be surprised by when you first find it out, and a little detail you use while playing constantly later on that you don’t think about much.

**Comment by MerpisMe** [comment]
ok then can we maybe make the lid animation have some dampening so it's not a linear animation
like ease out

**Comment by AViewFromTheTop** [comment]
> ok then can we maybe make the lid animation have some damping so it's not a linear animation
> like ease in similar to how the regular chest animation works

It uses the regular chest animation
The reason it’s different is that the value it uses to track its opening isn’t set to a stupidly high number, which is what makes the original work
You can’t have the lid only open partially without getting rid of that easing
I’m sure there’s a workaround, but I’m in a mood for chatting and relaxing atm and not modding- just wanted to point out the exact issue tho so maybe it’s easier to understand
