### ISSUE TITLE
[Feature Suggestion] Savanna Biome Config

### ISSUE THREAD

**Issue by eithli** [FrozenBlock/WilderWild#213]
Quite simple. A configuration option to turn off the generation of new baobab trees and termites in savannas.

The reason? A QoL change; for those who like some of the mod's features but would rather not have baobab trees and termites,

**Comment by AViewFromTheTop** [comment]
I won't be adding a config for this, as the amount of work it would require in order to add configs for all other new features would be astronomically stressful.
However, I *will* make a new biome tag for them so you can modify those with datapacks, much like many other features in the next version!

**Comment by AViewFromTheTop** [comment]
not for baobab though
